# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/petr/Documents/STMu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/petr/Documents/STMu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/petr/Documents/STMu/CMakeFiles /Users/petr/Documents/STMu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/petr/Documents/STMu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blinky_led

# Build rule for target.
blinky_led: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blinky_led
.PHONY : blinky_led

# fast build rule for target.
blinky_led/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/build
.PHONY : blinky_led/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

Src/main.obj: Src/main.c.obj
.PHONY : Src/main.obj

# target to build an object file
Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/main.c.obj
.PHONY : Src/main.c.obj

Src/main.i: Src/main.c.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/stm32f1xx_hal_msp.obj: Src/stm32f1xx_hal_msp.c.obj
.PHONY : Src/stm32f1xx_hal_msp.obj

# target to build an object file
Src/stm32f1xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_hal_msp.c.obj
.PHONY : Src/stm32f1xx_hal_msp.c.obj

Src/stm32f1xx_hal_msp.i: Src/stm32f1xx_hal_msp.c.i
.PHONY : Src/stm32f1xx_hal_msp.i

# target to preprocess a source file
Src/stm32f1xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_hal_msp.c.i
.PHONY : Src/stm32f1xx_hal_msp.c.i

Src/stm32f1xx_hal_msp.s: Src/stm32f1xx_hal_msp.c.s
.PHONY : Src/stm32f1xx_hal_msp.s

# target to generate assembly for a file
Src/stm32f1xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_hal_msp.c.s
.PHONY : Src/stm32f1xx_hal_msp.c.s

Src/stm32f1xx_it.obj: Src/stm32f1xx_it.c.obj
.PHONY : Src/stm32f1xx_it.obj

# target to build an object file
Src/stm32f1xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_it.c.obj
.PHONY : Src/stm32f1xx_it.c.obj

Src/stm32f1xx_it.i: Src/stm32f1xx_it.c.i
.PHONY : Src/stm32f1xx_it.i

# target to preprocess a source file
Src/stm32f1xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_it.c.i
.PHONY : Src/stm32f1xx_it.c.i

Src/stm32f1xx_it.s: Src/stm32f1xx_it.c.s
.PHONY : Src/stm32f1xx_it.s

# target to generate assembly for a file
Src/stm32f1xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/stm32f1xx_it.c.s
.PHONY : Src/stm32f1xx_it.c.s

Src/syscalls.obj: Src/syscalls.c.obj
.PHONY : Src/syscalls.obj

# target to build an object file
Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/syscalls.c.obj
.PHONY : Src/syscalls.c.obj

Src/syscalls.i: Src/syscalls.c.i
.PHONY : Src/syscalls.i

# target to preprocess a source file
Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/syscalls.c.i
.PHONY : Src/syscalls.c.i

Src/syscalls.s: Src/syscalls.c.s
.PHONY : Src/syscalls.s

# target to generate assembly for a file
Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/syscalls.c.s
.PHONY : Src/syscalls.c.s

Src/sysmem.obj: Src/sysmem.c.obj
.PHONY : Src/sysmem.obj

# target to build an object file
Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/sysmem.c.obj
.PHONY : Src/sysmem.c.obj

Src/sysmem.i: Src/sysmem.c.i
.PHONY : Src/sysmem.i

# target to preprocess a source file
Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/sysmem.c.i
.PHONY : Src/sysmem.c.i

Src/sysmem.s: Src/sysmem.c.s
.PHONY : Src/sysmem.s

# target to generate assembly for a file
Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/Src/sysmem.c.s
.PHONY : Src/sysmem.c.s

startup_stm32f103xe.obj: startup_stm32f103xe.s.obj
.PHONY : startup_stm32f103xe.obj

# target to build an object file
startup_stm32f103xe.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinky_led.dir/build.make CMakeFiles/blinky_led.dir/startup_stm32f103xe.s.obj
.PHONY : startup_stm32f103xe.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... STM32_Drivers"
	@echo "... blinky_led"
	@echo "... Src/main.obj"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/stm32f1xx_hal_msp.obj"
	@echo "... Src/stm32f1xx_hal_msp.i"
	@echo "... Src/stm32f1xx_hal_msp.s"
	@echo "... Src/stm32f1xx_it.obj"
	@echo "... Src/stm32f1xx_it.i"
	@echo "... Src/stm32f1xx_it.s"
	@echo "... Src/syscalls.obj"
	@echo "... Src/syscalls.i"
	@echo "... Src/syscalls.s"
	@echo "... Src/sysmem.obj"
	@echo "... Src/sysmem.i"
	@echo "... Src/sysmem.s"
	@echo "... startup_stm32f103xe.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

